---
title: "Data types"
format: html
---
# Instructions

This week, you learned about three data types in pandas---strings, datetimes, and categoricals.

In this milestone, you'll parse the declaration dates in the data set, extract the month of each date, and then create a variable that records the total number of disaster declarations for Spring, Summer, Fall, and Winter.

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-fema/assets/disasters_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None) # Show all table columns on print
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```

## Data types

In this milestone, you'll use a sorted categorical variable to plot total number of declarations by season in chronological order.

## Recreation

### Part 1 - Import

Use the code chunk below to read the data from the data file `disasters.csv`,
which is stored in the `data/` folder in your working directory.
Be sure to save the data set to a variable named `disasters`.

```{python}
#| label: 'recreation-import'

```

### Part 2 - Seasons

Run the code below to see a table. *Note:* Pay attention to the very last column.

```{python}
#| label: 'recreate-this'
solution = pd.read_csv('data/milestone05.csv')
solution
```

To recreate this table, you will need to:

1. Convert the `declaration_date` column into a pandas `date` type
2. Use `.dt.month` to get the month number of each date and save the result as a new column named `month`
3. Write a function that will recode the values of `month` to make a new variable named `season` such that:

  -  Months 1, 2, 3 = 'Winter'
  -  Months 4, 5, 6 = 'Spring'
  -  Months 7, 8, 9 = 'Summer'
  -  Months 10, 11, 12 = 'Fall'

4. Apply your function to the data set to create a new column that recodes the month integers to seasons.

Work in the code chunk below. Save the result as `disasters`.

```{python}
#| label: 'recreation-seasons'

```

Run the following code chunk to test whether you have the same answer as the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
disasters.compare(solution)
```

### Part 3 - The role of category order in visualizations

Now that you have a `season` variable, you can compute and visualize summaries for each season in the same manner as in previous milestones. Run the chunk below to view a summary table.

```{python}
#| label: 'summary'

seasons_summary = (disasters
  .groupby(['season'])
  .size()
  .reset_index()
  .rename(columns={0: 'n_declarations'})
)
seasons_summary
```

After you have run the chunk above to create `seasons_summary`, run the chunk below to visualize the data of `seasons_summary`.

```{python}
#| label: 'summary_plot'

from plotnine import ggplot, aes, geom_col, labs

p1 = (ggplot(seasons_summary, aes(x='season', y='n_declarations'))
  + geom_col()
  + labs(title='Total Disaster Declarations by Season',
         y='# declarations')
)
ggplot.show(p1)
```

This is a nice plot, but the order of seasons on the x axis is arbitrary (alphabetical). We may want to give the seasons a more principled order before we publish this plot.

#### Visualization

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone05.png` to open an image in the Editor pane

Consider this plot. Notice that the x axis is now ordered chronologically. Your task is to recreate this plot.

We recommend that you:

1.  Convert the `season` column in `seasons_summary` into a sorted, Categorical column.
    *Hint:* Use the function `pd.Categorical()`
2.  Use the modified `season` column to recreate the plot.
3.  Import and use `theme_bw()` as the plot theme.
4.  Save your plot as `p2` and use `ggplot.show(p2)` to display it.

```{python}
#| label: 'recreation-visualize-1'

```

## Extension

Using the code chunk below, investigate a research question about this data, using the skills you have learned this week and in previous weeks of Academy. Some ideas:

1. Use data visualization to investigate if there is a seasonal pattern in financial IHP awards - for the entire data set, for certain states, and/or FEMA regions.
2. Is there a month-by-month pattern for number of declarations (or another variable of your choice)? Does this vary if you focus on certain states or FEMA regions?
3. Looking within a month, do you see any pattern in number of declarations (or another variable of your choice) based on calendar day? Day of the week?
4. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. If your data set contains date, string, or categorical information, use a pandas function to correctly format and manipulate your variables.
3. Using a table or graph, present a meaningful subset of your modified data

```{python}
#| label: 'extension'

```
