---
title: "Wrangle rows and columns"
format: html
---
# Instructions

This week, you learned about several more pandas methods and attributes. These functions help you work with the columns in your data set.

You'll use these skills to add a new column that contains the cumulative total financial Individual Housing Program (IHP) awarded for a subset of the disaster declarations in the state of New York.

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-fema/assets/disasters_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None) # Show all table columns on print
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```

## Wrangle rows and columns

In this milestone, you'll create a new column that contains the cumulative financial Individual Housing Program (IHP) awarded for a subset of the disaster declarations in the state of New York.

## Recreation

### Part 1 - Import

First, import your data set:

1. Use the code chunk below to read the data from the data file `disasters.csv`,
which is stored in the `data/` folder in your working directory
2. Save the data set to a variable named `disasters`

```{python}
#| label: 'recreation-import'

```

### Part 2 - Create columns

Run the code below to see a table.

```{python}
#| label: 'recreate-this'
#| message: false

solution = pd.read_csv('data/milestone02.csv')
solution
```

Your task is to use what you've learned to transform `disasters` into this table.

You will need to:

1. Subset `disasters` for records where `ih_program_declared` is `1` and the `state` is `'NY'`. Save the result as a new data set called `subset`.
2. Sort the values in `subset` by `declaration_date` from earliest date to latest date.
3. Create a new column in `subset` named `cumul_total_ihp_awarded`, which contains the cumulative sum of the `total_ihp_awarded` column. *Hint:* use the `.cumsum()` function to do this.

Work in the code chunk below for your table transformation:

```{python}
#| label: 'recreation-create'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
subset.reset_index(drop=True).round(4).compare(solution.round(4))
```

### Part 3 - Visualize

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone02.png` to open an image in the Editor pane

Your task is to recreate this plot using your updated version of `subset`.
Use plotnine functions and the `subset` data set in the following chunk to recreate the plot.
Save your plot as `p1` and use `ggplot.show(p1)` to display it.

```{python}
#| label: 'recreation-visualize'

# Remember to import the plotnine functions that you'll be using.
# You can add them to the `setup` chunk at the top to keep your code organized.

```

## Extension

Using the code chunk below, investigate a research question about this data, using the additional data wrangling skills you learned this week. Some ideas:

1. This milestone focused on the cumulative financial IHP awarded for disaster declarations in New York. What patterns do you see in `cumul_total_ihp_awarded` for specific incident types within New York?
2. Use the `total_ha_awarded` and `total_ona_awarded` columns to explore patterns of total Housing Assistance (HA) and Other Needs Assistance (ONA) awarded over time for qualifying disasters in New York or elsewhere.
3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Create at least one new variable in your data set using mathematical operations
3. Use your updated data set to create at least one graph and/or table

```{python}
#| label: 'extension'

```
