---
title: "Summarize data"
format: html
---
# Instructions

This week, you learned about several more pandas methods.

In this milestone you'll group the data by FEMA region and then summarize the results to calculate the grand total of financial IHP awards across qualifying disasters.

To learn more about the variables contained in the data set,
refer to the data dictionary [here](https://rstudio.github.io/academy-python-fema/assets/disasters_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None) # Show all table columns on print
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```

## Summarize data

In this milestone you'll use groupwise summaries to compute the grand total of financial IHP awards across qualifying disasters and then plot the results.

## Recreation

### Part 1 - Import

Before you begin, you will need to import the `disasters_with_regions` data set:

1. Read the data from the data file `disasters_with_regions.csv`, which is stored in the `data/` folder in your working directory.
2. Save the data set to a variable named `disasters_with_regions`.

Work in the code chunk below:

```{python}
#| label: 'recreation-import'

```

### Part 2 - Compute total eligible applicants

Run the code below to compute the total number of applicants deemed eligible for the Individual Housing Program for qualifying disasters (i.e., disasters for which the IHP program was declared) that occurred in FEMA region 1.

```{python}
#| label: 'region-1-eligible'
subset = disasters_with_regions.loc[(disasters_with_regions['ih_program_declared'] == 1) & (disasters_with_regions['region'] == 1)]
subset['n_ihp_eligible'].sum()
```

### Part 3 - Summarize data

Next, you'll create a summary table containing the overall sum of `n_ihp_eligible` and `total_ihp_awarded` for each `region` across qualifying disasters.

Run the code below to see a table.

```{python}
#| label: 'recreate-this'
solution = pd.read_csv('data/milestone04.csv')
solution
```

Your task is to use what you've learned about functions and grouped summaries to transform `disasters_with_regions` into this table.

You will need to:

1. Subset `disasters_with_regions` for records where `ih_program_declared` is `1`. *Hint:* Remember that `.loc[]` is another way to subset a pandas DataFrame.
2. Group the data by `region`.
3. Summarize the total sum of `n_ihp_eligible` and `total_ihp_awarded` for each group. *Hint:* Use `.agg()` to do so.
4. Reset the row values using `.reset_index()`.
5. Create a new column called `total_ihp_awarded_millions` that contains `total_ihp_awarded` divided by 1000000. This will make the values easier to interpret when we plot them later.

Work in the code chunk below. Save the result as `ihp_summary`. We will use the result in Part 4.

```{python}
#| label: 'recreation-summary'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
ihp_summary.round(6).compare(solution.round(6))
```

### Part 4 - Visualize it

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone04.png` to open an image in the Editor pane

Finally, use the new `ihp_summary` data to recreate this plot.
Save your plot as `p1` and use `ggplot.show(p1)` to display it.

*Hint:* In plotnine, `aes()` has 2 internal functions that can be used to transform the variables being mapped: `factor()` and `reorder()`. Instead of using `x = 'region'` to create your plot, use `x = 'factor(region)'` to treat `region` as a category.

```{python}
#| label: 'recreation-visualize'

```

## Extension

Using the code chunk below, investigate a research question about this data, using the additional data wrangling skills you learned this week. Some ideas:

1. How does the grand total of financial IHP awarded compare across different incident types within a single FEMA region? Multiple FEMA regions?
2. We have not yet explored the variables `total_ha_awarded` or `total_ona_awarded`; what can you learn about the overall total of each of these variables across different FEMA regions?
3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Use `.groupby()` and `.apply()` or `.agg()` to produce a summary table from your data
3. Create a related graph of this data subset using plotnine

```{python}
#| label: 'extension'

```
