---
title: "Write functions"
format: html
---
# Instructions

This week, you learned how to write and apply your own functions.

You'll use these skills to add a column that contains the FEMA region where the disaster occurred (FEMA regions: https://www.fema.gov/about/organization/regions).

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-fema/assets/disasters_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None) # Show all table columns on print
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```

## Write functions

As we work towards building polished reports and plots, it may be useful to explore patterns across FEMA regions rather than across individual states.
In this milestone, you'll create a new column that contains the FEMA region a given record is associated with.

## Recreation

### Part 1 - Import

First, import your data set, as you have in past milestones:

1. Read the data from the data file `disasters.csv`, stored in the `data/` folder in your working directory.
2. Save the data set to a variable named `disasters`.

Work in the code chunk below.

```{python}
#| label: 'recreation_import'

```

### Part 2 - Write a function

Your task is to write a function named `get_region()` that will accept a single string as input (e.g., `'NY'`) and return the associated region as an integer (e.g., `2`).
If the input string does not match any of the states below, return `None`.

Below are the ten regions and the associated states:

- 1 = 'CT', 'ME', 'MA', 'NH', 'RI', 'VT'
- 2 = 'NJ', 'NY', 'PR', 'VI'
- 3 = 'DE', 'MD', 'PA', 'VA', 'DC', 'WV'
- 4 = 'AL', 'FL', 'GA', 'KY', 'MS', 'NC', 'SC', 'TN'
- 5 = 'IL', 'IN', 'MI', 'MN', 'OH', 'WI'
- 6 = 'AR', 'LA', 'NM', 'OK', 'TX'
- 7 = 'IA', 'KS', 'MO', 'NE'
- 8 = 'CO', 'MT', 'ND', 'SD', 'UT', 'WY'
- 9 = 'AZ', 'CA', 'HI', 'NV', 'GU', 'AS', 'MP', 'MH', 'FM', 'PW'
- 10 = 'AK', 'ID', 'OR', 'WA'

```{python}
#| label: 'recreation-function'

```

Run the following code chunk to test your function on a few different values:

```{python}
#| label: 'compare_results'

get_region('VT') # should return 1
get_region('MD') # should return 3
get_region('OR') # should return 10
```

### Part 3 - Apply

1. Using your function, add a new column to `disasters` called `region` that contains the region associated with each state.
2. Save the resulting table as `data/disasters_with_regions.csv`. *Note:* when saving, set `index=False`.

```{python}
#| label: 'recreation_apply'

```

## Extension

Use the code chunk(s) below to extend your work.
Try something that you can learn from experimentation, a help page, or a package website.

Consider:

1. Writing a function that subsets the data set for a given FEMA region and creates a visualization.
2. Writing a function that returns the corresponding Census Bureau Region or Division (e.g., Northeast, Midwest, South, West) associated with each US state (Census Bureau regions and divisions: https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf).
3. Something else.

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Write a function that performs an operation on your data
3. Call the function, or use `.apply()` to apply it to every row in the data set

```{python}
#| label: 'extension'

```
